import java.util.*;

public class Courses {
    /**
     * Graph for courses:
     * The point is to have a graph of courses needed
     * to reach the desired course
     */
    private Set<Course> start;
    private Map<String,Course> courseSet;
    private Map<Integer,List<Course>> courseGroup;
    private Set<Course> completed;

    private class Course{
        /**
         * Node for the graph:
         * It contains the classes for which the
         * Class is co and pre-requisite for.
         * Since the amount is not known LinkedList
         * is chosen for it's adding of O(1)
         */
        private String name;
        private LinkedList<Course> prerequisiteFor;
        private LinkedList<Course> corequisiteFor;
        /**
         * The sets refer to which groups are needed to get to
         * this one.
         */
        private List<List<Course>> prerequisiteGroups;
        private List<List<Course>> corequisiteGroups;


    }
    //constructor
    public Courses(Map<String, List<List<String>>> preReqData, Map<String, List<List<String>>> coReqData) {
    /*
    DESCRIPTION:
    Constructor that initializes the course data structures by parsing raw prerequisite and corequisite map payloads into an object-oriented dependency graph. It then scans the graph to identify and register starting entry-level courses.

    CRUCIAL NOTICES:
    - It is crucial to evaluate the inverse conditions (`completed == null || !completed.contains(c)`) alongside checking for empty dependency groups when identifying starting classes. This isolation ensures that courses already marked as historically completed are not erroneously flagged as active "start" courses for the upcoming progression plan, despite having structurally empty prerequisites.
    - It is crucial to execute `MapParser` for both datasets sequentially before determining start nodes. This ensures that the global `courseSet` registry and individual node structures are completely mapped and fully linked with both edge directions before the algorithm evaluates true start availability.

    INPUT:
    - Map<String, List<List<String>>> preReqData: Raw structural mappings defining the prerequisite constraints.
    - Map<String, List<List<String>>> coReqData: Raw structural mappings defining the corequisite constraints.

    OUTPUT:
    - None (Constructor that initializes instance states).

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - MapParser()

      [STANDARD METHODS]
      - courseSet.values()
      - list.isEmpty()
      - completed.contains()
      - start.add()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(P + C + V), where P and C represent the nested string evaluation costs inside the two `MapParser` operations, and V is the total number of unique course vertices checked in the linear startup sweep.
    - Space Complexity: O(V) to instantiate the underlying `HashMap` tables and configure the `start` set allocation structures within instance states.
    - Leverages an initialization mapping sweep to construct structural dependency trees and extract root nodes (nodes with an indegree of zero) to establish a safe graph traversal foundation.
    */
    }

    public String toString() {
    /*
    DESCRIPTION:
    Generates a human-readable text representation of the course progression schedule. It prints a list of completed courses followed by a chronological, semester-by-semester breakdown of the topologically sorted course layers.

    CRUCIAL NOTICES:
    - It is crucial to utilize the `StringJoiner` utility class configured with delimiter, prefix, and suffix constraints (`", "`, `"["`, `"]"`). This replaces manual looping flag hacks and cleanly ensures that inner elements are cleanly formatted into comma-separated blocks without risking illegal trailing symbols.
    - It is crucial to iterate through a `LinkedList<Set<Course>>` structure generated by `topologicalSort()`. Utilizing a `Set` for each sequential semester group is necessary to safely eliminate duplicate entries and track simultaneous scheduling tracks reliably.
    - It is crucial to include a safe structural check (`completed != null && !completed.isEmpty()`) before processing history. This ensures that classes evaluated without any prior completed training background render an empty token balance instead of throwing a NullPointerException.

    INPUT:
    - None (Operates entirely via implicit instance fields: completed, alongside the topologicalSort execution path).

    OUTPUT:
    - String: A formatted multi-line text block detailing historical tracks and upcoming semester configurations.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - topologicalSort()

      [STANDARD METHODS]
      - completed.isEmpty()
      - completedJoiner.add()
      - joiner.add()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(T + V), where T is the performance overhead of executing the `topologicalSort()` solver step, and V corresponds to the number of completed and scheduled course instances processed across the string generation step.
    - Space Complexity: O(T + V) to generate and construct temporary textual string segments within memory allocations.
    - Employs an iterative tracking sweep utilizing string accumulation buffers to transform structured graph components into standardized text matrices.
    */
        return "";
    }

    public String toJson() {
    /*
    DESCRIPTION:
    Serializes the final calculated course progression schedule into a structured JSON string. It invokes the topological sorting pipeline to determine semester layouts, and then manually iterates through both the 'completed' course registry and the resulting sorted semester lists to output standard JSON arrays.

    CRUCIAL NOTICES:
    - It is crucial to use standard `Iterator` patterns (`it.hasNext()` and `semesterIt.hasNext()`) inside the dynamic text builders instead of simple foreach loops. This guarantees that separation commas are accurately placed *between* string values or array sub-blocks without trailing endings that would break standard JSON formatting syntax.
    - It is crucial to perform an explicit null validation check on the global `completed` set collection before accessing it. If this safety validation is omitted, classes that run with zero pre-completed courses will trigger a fatal NullPointerException during runtime serialization.

    INPUT:
    - None (Operates entirely via implicit instance fields: completed, alongside the topologicalSort execution path).

    OUTPUT:
    - String: A formatted JSON payload containing distinct 'completed' and 'semesters' nested data arrays.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - topologicalSort()

      [STANDARD METHODS]
      - json.append()
      - completed.iterator()
      - sortedGraph.iterator()
      - semester.iterator()
      - it.hasNext()
      - it.next()
      - courseIt.next()
      - semesterIt.next()
      - json.toString()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(T + V), where T is the underlying execution runtime cost of the `topologicalSort()` calculation step, and V represents the total number of individual course objects being structurally read and serialized across both loops.
    - Space Complexity: O(T + V) auxiliary space required to build, preserve, and output the text stream arrays within the active string builder memory frame.
    - Employs a precise procedural text compilation strategy to cleanly format deep multi-dimensional class arrays directly into clean, human-readable JSON payloads.
    */
        return "";
    }

    //helper methods
    private void MapParser(Map<String, List<List<String>>> data, String type) {
    /*
    DESCRIPTION:
    Parses a raw multi-level string map of course requirements and transforms it into an object-oriented dependency graph. It maps text identifiers to unique Course objects, populates prerequisite/corequisite reference lists, handles "COMPLETED" status overrides, and wires bidirectional graph edges.

    CRUCIAL NOTICES:
    - It is crucial to perform deep index checks (`!data.get(keyName).isEmpty() && data.get(keyName).get(0).get(0).equalsIgnoreCase("COMPLETED")`) to catch hardcoded string tokens. When found, the course must be appended to the global `completed` tracking set, and the raw data payload must be wiped out with an empty list allocation to prevent completed courses from continuing to register dangling dependencies.
    - It is crucial to check the structural type input ("pre" or "co") inside the innermost loop to configure bidirectional graph link bindings. It establishes downstream visibility by tracking who the inner `valCourse` is a dependency for (`prerequisiteFor` or `corequisiteFor`) while mapping the upstream dependency categories (`prerequisiteGroups` or `corequisiteGroups`) directly onto the primary `keyCourse`.

    INPUT:
    - Map<String, List<List<String>>> data: The raw nested textual dataset representing prerequisite or corequisite string arrays.
    - String type: A literal identifier string used to branch parsing logic into either "pre" or "co" processing pipelines.

    OUTPUT:
    - void: Modifies instance graph entities and updates local/global course states in-place.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - getCourseFromSet()

      [STANDARD METHODS]
      - data.keySet()
      - data.get()
      - data.put()
      - list.isEmpty()
      - string.equalsIgnoreCase()
      - list.add()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(K * G * C), where K is the number of master keys in the map, G is the maximum number of structural dependency groups per key, and C is the average count of course strings grouped inside those arrays.
    - Space Complexity: O(K * G * C) to allocate, structure, and hold the newly linked domain object references, lists, and reference trees.
    - Implements an explicit nested matrix parsing algorithm designed to transition unstructured text payloads into an interconnected object-oriented adjacency graph.
    */
    }

    private Course getCourseFromSet(String name) {
    /*
    DESCRIPTION:
    Retrieves an existing Course domain object from a global tracking map by its name. If the course is not found, it initializes a new Course instance, configures its structural identity attributes, caches it within the tracking map, and returns the reference.

    CRUCIAL NOTICES:
    - It is crucial to perform `name = name.toUpperCase()` immediately at the start of the method. This standardizes the text inputs and prevents duplicate Course objects from being created in the mapping table due to casing differences (e.g., matching "cs101" and "CS101" to the exact same memory instance).
    - It is crucial to handle the absence of a course by dynamically instantiating, naming, and inserting it into `courseSet` in-place. This guarantees that downstream structural logic never runs into null pointer exceptions when referencing dependencies that haven't been fully explored or declared yet.

    INPUT:
    - String name: The textual identifier or code designation of the course to retrieve or create.

    OUTPUT:
    - Course: The synchronized domain object matching the normalized course name.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - None

      [STANDARD METHODS]
      - name.toUpperCase()
      - courseSet.containsKey()
      - courseSet.put()
      - courseSet.get()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(1) average time complexity, as lookup, insertion, and initialization operations inside the underlying tracking hash map take constant time.
    - Space Complexity: O(1) auxiliary space, though it potentially adds a new singular course element allocation into the pre-existing global hash map storage environment.
    - Implements a programmatic creation pattern (Lazy Initialization / Factory pattern variant) ensuring strict reference uniqueness across the active course entity graph network.
    */
        return null;
    }

    private LinkedList<Set<Course>> topologicalSort() {
    /*
    DESCRIPTION:
    Executes a specialized layered topological sort algorithm to group courses into valid sequential semesters. It resolves standard directional prerequisites alongside cyclic, simultaneous corequisite dependencies using a double-filtering convergence loop.

    CRUCIAL NOTICES:
    - It is crucial to use a nested `do-while` convergence loop with a `changed` flag when filtering candidates by corequisites. Removing a course that fails its corequisite check might break the corequisite requirements of *other* courses in that same tentative semester pool, so the algorithm must re-evaluate iteratively until the candidate pool stops shrinking to avoid invalid schedules.
    - It is crucial to build a `hypotheticalVisited` timeline by merging the current `visited` courses with the full active `semester` candidate pool before calling `processRequisite` for corequisites. Corequisites are taken during the *same* term, so a course's corequisite requirement is satisfied if its partner course is also part of this semester's candidate pool.
    - It is crucial to initialize the `visited` tracking set with the `completed` courses set right at the start. If previously cleared courses are not registered as visited before the loops execute, the algorithm will try to schedule completed classes again, generating wrong entry nodes and breaking the sorting path.

    INPUT:
    - None (Operates entirely via implicit instance fields: completed, start, courseSet).

    OUTPUT:
    - LinkedList<Set<Course>>: A chronological list of course sets, where each set represents a safe, independent semester plan.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - processRequisite()

      [STANDARD METHODS]
      - completed.isEmpty()
      - preIndegree.get()
      - eligibleCourses.isEmpty()
      - hypotheticalVisited.addAll()
      - coIndegree.get()
      - validCo.contains()
      - toRemove.isEmpty()
      - semester.removeAll()
      - visited.addAll()
      - result.add()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(I * P * C), where I is the number of semesters (outer loop iterations), P is the number of inner convergence passes required to stabilize a semester pool, and C is the total cost of processing course sets via `processRequisite`.
    - Space Complexity: O(V) to maintain snapshot sets (`visited`, `hypotheticalVisited`, `semester`, and `toRemove`) proportional to the total number of course vertices in the graph network.
    - Implements an advanced, multi-pass variant of Kahn's topological sorting algorithm that layers dependency filtering to reconcile both sequential (prerequisite) and simultaneous (corequisite) structural graph edges.
    */
        return new java.util.LinkedList<>();
    }


    private Map<Integer, Set<Course>> processRequisite(Set<Course> visited, int iteration, String type, Set<Course> innerVisited) {
    /*
    DESCRIPTION:
    Calculates the unfulfilled dependency counts (indegrees) for all courses in the global dataset during a specific cycle, grouping courses by the number of remaining requirement groups they have left.

    CRUCIAL NOTICES:
    - It is crucial to use `innerVisited` instead of the global `visited` set when calculating unfulfilled groups via `getNumberOfGroups`. This is because `innerVisited` tracks transient additions within a single calculation round, preventing ahead-of-time evaluation errors across independent dependency branches.
    - It is crucial to skip over courses present in `start`, `completed`, or `visited` right at the beginning of the loop. If this exclusion check is skipped, already fulfilled or starting courses will wrongly have their indegrees recalculated, corrupting topological ordering and creating infinite processing cycles.
    - It is crucial to seed the map with an explicit key of `0` containing the `start` courses during `iteration==0`. This explicitly establishes the base layer of the dependency graph, forcing downstream logic to process root entries first.

    INPUT:
    - Set<Course> visited: The historical registry of courses completely processed across all preceding iterations.
    - int iteration: The current processing loop index used to trigger the base-case seeding logic.
    - String type: The targeted dependency group classification mapping literal ("pre" or "co").
    - Set<Course> innerVisited: A localized snapshot collection capturing ongoing visibility states for the current cycle.

    OUTPUT:
    - Map<Integer, Set<Course>>: A histogram-like map structure associating an unfulfilled group count (indegree) key to the set of courses sitting at that exact dependency depth.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - getNumberOfGroups()

      [STANDARD METHODS]
      - courseSet.values()
      - start.contains()
      - completed.contains()
      - visited.contains()
      - indegree.containsKey()
      - indegree.get()
      - indegree.put()
      - set.add()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(C * G * M), where C is the total number of courses in `courseSet`, G is the max number of dependency groups per course, and M is the average number of courses per group due to the nested `getNumberOfGroups` evaluation.
    - Space Complexity: O(C) to instantiate, cluster, and isolate courses into their corresponding integer-keyed bucketing arrays.
    - Utilizes a specialized bucketing strategy reminiscent of Kahn’s topological sorting algorithm, cataloging graph nodes dynamically based on remaining constraints.
    */
        return new java.util.HashMap<>();
    }

    private int getNumberOfGroups(Course course, String type, Set<Course> visited) {
    /*
    DESCRIPTION:
    Calculates the number of prerequisite or corequisite groups for a given course that have not been fulfilled yet by checking them against a set of already visited/completed courses.

    CRUCIAL NOTICES:
    - It is crucial to use `Collections.disjoint(group, visited)` to determine group fulfillment. If a group shares zero elements with the visited set, it means no courses from that option group have been completed, making the entire group count as remaining/unfulfilled.
    - It is crucial to pass an explicit classification type ("pre" or "co") to dynamically target either `course.prerequisiteGroups` or `course.corequisiteGroups`, throwing a runtime error for invalid inputs to prevent silent state failures.

    INPUT:
    - Course course: The custom object instance representing the target course being analyzed.
    - String type: A literal identifier string used to look up either "pre" or "co" structural data groups.
    - Set<Course> visited: A collection containing the unique registry of courses that have already been taken or processed.

    OUTPUT:
    - int: The total count of unfulfilled or completely remaining course dependency groups.

    NON-TRIVIAL EXTERNAL CLASSES USED:
    - Course: Custom domain model object tracking prerequisite and corequisite collection structures.

    CALLED METHODS:
      [CUSTOM METHODS]
      - None

      [STANDARD METHODS]
      - type.equalsIgnoreCase()
      - groups.isEmpty()
      - group.isEmpty()
      - Collections.disjoint()

    ALGORITHM & COMPLEXITY:
    - Time Complexity: O(G * M), where G is the number of groups under the selected course and M is the average number of course entries per group (assuming constant time O(1) hash set lookups within the disjoint call).
    - Space Complexity: O(1) auxiliary space as it computes metrics on references in-place without generating data collections.
    - Employs an iterative filtering algorithm leveraging relational disjunction evaluations to dynamically tally isolated unfulfilled criteria sets.
    */
        return 0;
    }



}